-- ============================================================
-- 014_share_flow.sql
-- Direct sharing flow (Build Guide Step 21 / Spec §6.1).
--
-- A fresh first-hop share is: original_owner_id = source_vendor_id = the owner,
-- recipient_id = the chosen vendor, chain_depth = 0. Tokens are generated by the
-- shares table DEFAULT.
--
-- These run SECURITY DEFINER because they must (a) insert notifications rows for
-- OTHER vendors (notifications_own RLS blocks that from the client) and
-- (b) read across vendors/inventory while staying scoped to auth.uid().
-- The public preview RPC is the only one granted to anon — and it deliberately
-- never exposes original_owner_id (the privacy chain).
-- ============================================================

-- ------------------------------------------------------------
-- Direct share to N connected vendors. Dedupes against existing active
-- depth-0 shares so shared_count is incremented ONLY by genuinely new vendors.
-- Returns the number of new shares created.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_direct_shares(p_inventory_id uuid, p_recipient_ids uuid[])
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  me         uuid := auth.uid();
  rid        uuid;
  new_count  int := 0;
  item_title text;
  my_company text;
BEGIN
  IF me IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_recipient_ids IS NULL THEN RETURN 0; END IF;

  SELECT title INTO item_title FROM inventory WHERE inventory_id = p_inventory_id AND vendor_id = me;
  IF item_title IS NULL THEN RAISE EXCEPTION 'You do not own this item'; END IF;
  SELECT company_name INTO my_company FROM vendors WHERE id = me;

  FOREACH rid IN ARRAY p_recipient_ids LOOP
    IF rid IS NULL OR rid = me THEN CONTINUE; END IF;
    -- Already shared with this vendor? skip (no double count).
    IF EXISTS (
      SELECT 1 FROM shares s
      WHERE s.inventory_id = p_inventory_id AND s.recipient_id = rid
        AND s.source_vendor_id = me AND s.chain_depth = 0 AND s.status = 'active'
    ) THEN CONTINUE; END IF;

    INSERT INTO shares (inventory_id, original_owner_id, source_vendor_id, recipient_id, parent_share_id, chain_depth, status)
    VALUES (p_inventory_id, me, me, rid, NULL, 0, 'active');

    INSERT INTO notifications (vendor_id, type, title, body, related_id)
    VALUES (rid, 'share_received', COALESCE(my_company, 'A vendor') || ' shared an item with you', item_title, p_inventory_id);

    new_count := new_count + 1;
  END LOOP;

  IF new_count > 0 THEN
    UPDATE inventory SET shared_count = shared_count + new_count, updated_at = NOW()
    WHERE inventory_id = p_inventory_id;
  END IF;
  RETURN new_count;
END;
$$;
REVOKE ALL ON FUNCTION public.create_direct_shares(uuid, uuid[]) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.create_direct_shares(uuid, uuid[]) TO authenticated;

-- ------------------------------------------------------------
-- Share to a single email. If it matches a registered vendor → behave like a
-- direct network share (shares row + notification + shared_count). Otherwise
-- it's an invite: ensure a manual_vendors reference exists and mint a
-- public-forward share (recipient_id = null) whose link is emailed to them.
-- Returns { matched, token, recipient_id }.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.share_by_email(p_inventory_id uuid, p_email text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  me         uuid := auth.uid();
  v_email    text := lower(trim(p_email));
  v_match    uuid;
  v_token    text;
  item_title text;
  my_company text;
BEGIN
  IF me IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF v_email = '' THEN RAISE EXCEPTION 'Email is required'; END IF;

  SELECT title INTO item_title FROM inventory WHERE inventory_id = p_inventory_id AND vendor_id = me;
  IF item_title IS NULL THEN RAISE EXCEPTION 'You do not own this item'; END IF;
  SELECT company_name INTO my_company FROM vendors WHERE id = me;

  SELECT id INTO v_match FROM vendors WHERE lower(email) = v_email AND id <> me LIMIT 1;

  IF v_match IS NOT NULL THEN
    IF EXISTS (
      SELECT 1 FROM shares s
      WHERE s.inventory_id = p_inventory_id AND s.recipient_id = v_match
        AND s.source_vendor_id = me AND s.chain_depth = 0 AND s.status = 'active'
    ) THEN
      SELECT token INTO v_token FROM shares
      WHERE inventory_id = p_inventory_id AND recipient_id = v_match AND source_vendor_id = me
        AND chain_depth = 0 AND status = 'active'
      ORDER BY created_at DESC LIMIT 1;
    ELSE
      INSERT INTO shares (inventory_id, original_owner_id, source_vendor_id, recipient_id, parent_share_id, chain_depth, status)
      VALUES (p_inventory_id, me, me, v_match, NULL, 0, 'active')
      RETURNING token INTO v_token;

      INSERT INTO notifications (vendor_id, type, title, body, related_id)
      VALUES (v_match, 'share_received', COALESCE(my_company, 'A vendor') || ' shared an item with you', item_title, p_inventory_id);

      UPDATE inventory SET shared_count = shared_count + 1, updated_at = NOW()
      WHERE inventory_id = p_inventory_id;
    END IF;
    RETURN jsonb_build_object('matched', true, 'token', v_token, 'recipient_id', v_match);
  END IF;

  -- Unregistered: keep a manual reference so the share is traceable when they sign up.
  IF NOT EXISTS (SELECT 1 FROM manual_vendors WHERE owner_vendor_id = me AND lower(email) = v_email) THEN
    INSERT INTO manual_vendors (owner_vendor_id, company_name, email, is_registered)
    VALUES (me, split_part(v_email, '@', 1), v_email, false);
  END IF;

  INSERT INTO shares (inventory_id, original_owner_id, source_vendor_id, recipient_id, parent_share_id, chain_depth, status)
  VALUES (p_inventory_id, me, me, NULL, NULL, 0, 'active')
  RETURNING token INTO v_token;

  RETURN jsonb_build_object('matched', false, 'token', v_token, 'recipient_id', null);
END;
$$;
REVOKE ALL ON FUNCTION public.share_by_email(uuid, text) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.share_by_email(uuid, text) TO authenticated;

-- ------------------------------------------------------------
-- Public, login-free preview of a share by token. Anyone with the link can see
-- basic item info + who shared it (the source vendor). NEVER returns
-- original_owner_id — the upstream supplier stays hidden on forwarded links.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_public_share(p_token text)
RETURNS TABLE (
  token             text,
  chain_depth       int,
  status            text,
  title             text,
  description       text,
  category          text,
  quantity          numeric,
  unit              text,
  origin            text,
  display_price     numeric,
  display_currency  text,
  forward_remark    text,
  shared_by_company text,
  shared_by_logo_url text,
  has_recipient     boolean
)
LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public, pg_temp
AS $$
  SELECT
    s.token, s.chain_depth, s.status,
    i.title, i.description, i.category, i.quantity, i.unit, i.origin,
    COALESCE(s.forward_price, i.price)       AS display_price,
    COALESCE(s.forward_currency, i.currency) AS display_currency,
    s.forward_remark,
    sv.company_name AS shared_by_company,
    sv.logo_url     AS shared_by_logo_url,
    (s.recipient_id IS NOT NULL) AS has_recipient
  FROM shares s
  JOIN inventory i ON i.inventory_id = s.inventory_id
  JOIN vendors sv  ON sv.id = s.source_vendor_id
  WHERE s.token = p_token AND s.status = 'active'
  LIMIT 1;
$$;
GRANT EXECUTE ON FUNCTION public.get_public_share(text) TO anon, authenticated;

-- ------------------------------------------------------------
-- Signed-in resolution of a token. Owners get a flag back; a public-forward
-- link (recipient_id null) is claimed by setting recipient_id = caller.
-- Returns { is_owner, share_id, inventory_id }.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.claim_share(p_token text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  me uuid := auth.uid();
  s  shares%ROWTYPE;
BEGIN
  IF me IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  SELECT * INTO s FROM shares WHERE token = p_token AND status = 'active' LIMIT 1;
  IF s.share_id IS NULL THEN RAISE EXCEPTION 'Share not found'; END IF;

  IF me = s.original_owner_id OR me = s.source_vendor_id THEN
    RETURN jsonb_build_object('is_owner', true, 'share_id', s.share_id, 'inventory_id', s.inventory_id);
  END IF;

  IF s.recipient_id IS NULL THEN
    UPDATE shares SET recipient_id = me, updated_at = NOW() WHERE share_id = s.share_id;
  END IF;

  RETURN jsonb_build_object('is_owner', false, 'share_id', s.share_id, 'inventory_id', s.inventory_id);
END;
$$;
REVOKE ALL ON FUNCTION public.claim_share(text) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.claim_share(text) TO authenticated;
